// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/danielgtaylor/huma/v2"
	"github.com/uptrace/bun"
	"google.golang.org/grpc"
	"starter-boilerplate/internal/shared/middleware"
	"starter-boilerplate/internal/user/app/service"
	"starter-boilerplate/internal/user/app/usecase"
	"starter-boilerplate/internal/user/domain/repository"
	"starter-boilerplate/internal/user/transport/consumer"
	"starter-boilerplate/internal/user/transport/contract"
	"starter-boilerplate/internal/user/transport/handler"
	"starter-boilerplate/pkg/amqp"
	"starter-boilerplate/pkg/event"
	"starter-boilerplate/pkg/jwt"
)

// Injectors from initialize.go:

func InitializeUserModule(db *bun.DB, api huma.API, grpcSrv *grpc.Server, manager *jwt.Manager, init middleware.Init, userRepository repository.UserRepository, profileRepository repository.ProfileRepository, bus event.Bus, broker *amqp.Broker) Module {
	userService := service.NewUserService(userRepository)
	tokenService := service.NewTokenService(manager)
	loginUseCase := usecase.NewLoginUseCase(userService, tokenService)
	loginHandler := handler.NewLoginHandler(loginUseCase)
	refreshUseCase := usecase.NewRefreshUseCase(userService, tokenService)
	refreshHandler := handler.NewRefreshHandler(refreshUseCase)
	getUserUseCase := usecase.NewGetUserUseCase(userService)
	getUserHandler := handler.NewGetUserHandler(getUserUseCase)
	registerUseCase := usecase.NewRegisterUseCase(userService, tokenService, bus)
	registerHandler := handler.NewRegisterHandler(registerUseCase)
	changePasswordUseCase := usecase.NewChangePasswordUseCase(userService, bus)
	changePasswordHandler := handler.NewChangePasswordHandler(changePasswordUseCase)
	handlersInit := handler.SetupHandlers(api, loginHandler, refreshHandler, getUserHandler, registerHandler, changePasswordHandler)
	contractInit := contract.SetupUserContract(grpcSrv, userRepository)
	profileService := service.NewProfileService(profileRepository)
	profileUpdaterConsumer := consumer.NewProfileUpdaterConsumer(profileService)
	consumerInit := consumer.SetupConsumers(broker, profileUpdaterConsumer)
	module := NewModule(handlersInit, contractInit, consumerInit)
	return module
}

// initialize.go:

type Module struct{}

func NewModule(_ handler.HandlersInit, _ contract.Init, _ consumer.Init) Module {
	return Module{}
}
