// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	huma2 "github.com/danielgtaylor/huma/v2"
	redis2 "github.com/redis/go-redis/v9"
	grpc2 "google.golang.org/grpc"
	"log/slog"
	"net/http"
	"starter-boilerplate/internal/shared/app"
	"starter-boilerplate/internal/shared/config"
	"starter-boilerplate/internal/shared/consumer"
	"starter-boilerplate/internal/shared/huma"
	"starter-boilerplate/internal/shared/jwt"
	"starter-boilerplate/internal/shared/logger"
	"starter-boilerplate/internal/shared/middleware"
	"starter-boilerplate/internal/shared/server"
	"starter-boilerplate/internal/user"
	"starter-boilerplate/internal/user/app/service"
	"starter-boilerplate/internal/user/infra/persistence"
	"starter-boilerplate/pkg/amqp"
	"starter-boilerplate/pkg/db"
	"starter-boilerplate/pkg/event"
	"starter-boilerplate/pkg/grpc"
	"starter-boilerplate/pkg/redis"
)

// Injectors from initialize.go:

func InitializeApp(ctx context.Context) *app.App {
	serveMux := server.SetupMux()
	configConfig := config.SetupConfig()
	appConfig := configConfig.App
	httpServer := server.SetupHTTPServer(serveMux, appConfig)
	dbConfig := configConfig.DB
	loggerConfig := configConfig.Logger
	slogLogger := logger.SetupLogger(loggerConfig)
	bunDB := db.Setup(ctx, dbConfig, slogLogger)
	api := huma.Setup(serveMux, appConfig)
	grpcConfig := configConfig.GRPC
	grpcServer := grpc.Setup(grpcConfig, slogLogger)
	jwtConfig := configConfig.JWT
	manager := jwt.NewJWTManager(jwtConfig)
	userRepository := persistence.NewUserRepository(bunDB)
	userLoaderCreator := service.NewUserLoaderCreator(userRepository)
	init := middleware.Setup(httpServer, api, manager, userLoaderCreator)
	profileRepository := persistence.NewProfileRepository(bunDB)
	amqpConfig := configConfig.AMQP
	connection := amqp.Setup(amqpConfig, slogLogger)
	broker := consumer.Setup(connection)
	publisher := broker.Publisher
	bus := event.NewEventBus(connection, publisher)
	consumerGroup := broker.Consumers
	module := user.InitializeUserModule(bunDB, api, grpcServer, manager, init, userRepository, profileRepository, bus, consumerGroup)
	redisConfig := configConfig.Redis
	client := redis.Setup(ctx, redisConfig, slogLogger)
	appApp := newApp(httpServer, configConfig, module, slogLogger, client, grpcServer, api, broker)
	return appApp
}

// initialize.go:

func newApp(httpSrv *http.Server, cfg *config.Config, _ user.Module, _ *slog.Logger, _ *redis2.Client, grpcSrv *grpc2.Server, api huma2.API, broker *amqp.Broker) *app.App {
	return app.New(httpSrv, cfg, grpcSrv, api, broker)
}
