// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	centrifuge2 "github.com/centrifugal/centrifuge"
	huma2 "github.com/danielgtaylor/huma/v2"
	redis2 "github.com/redis/go-redis/v9"
	grpc2 "google.golang.org/grpc"
	"log/slog"
	"net/http"
	"starter-boilerplate/internal/shared/app"
	"starter-boilerplate/internal/shared/centrifugenode"
	"starter-boilerplate/internal/shared/config"
	"starter-boilerplate/internal/shared/consumer"
	"starter-boilerplate/internal/shared/huma"
	"starter-boilerplate/internal/shared/jwt"
	"starter-boilerplate/internal/shared/logger"
	"starter-boilerplate/internal/shared/middleware"
	"starter-boilerplate/internal/shared/server"
	"starter-boilerplate/internal/user"
	"starter-boilerplate/pkg/amqp"
	"starter-boilerplate/pkg/centrifuge"
	"starter-boilerplate/pkg/db"
	"starter-boilerplate/pkg/event"
	"starter-boilerplate/pkg/grpc"
	"starter-boilerplate/pkg/outbox"
	"starter-boilerplate/pkg/redis"
)

// Injectors from initialize.go:

func InitializeApp(ctx context.Context) *app.App {
	serveMux := server.SetupMux()
	configConfig := config.SetupConfig()
	appConfig := configConfig.App
	httpServer := server.SetupHTTPServer(serveMux, appConfig)
	api := huma.Setup(serveMux, appConfig)
	grpcConfig := configConfig.GRPC
	loggerConfig := configConfig.Logger
	slogLogger := logger.SetupLogger(loggerConfig)
	grpcServer := grpc.Setup(grpcConfig, slogLogger)
	jwtConfig := configConfig.JWT
	manager := jwt.NewJWTManager(jwtConfig)
	dbConfig := configConfig.DB
	bunDB := db.Setup(ctx, dbConfig, slogLogger)
	repository := outbox.NewRepository(bunDB)
	outboxBus := outbox.NewOutboxBus(repository)
	amqpConfig := configConfig.AMQP
	connection := amqp.Setup(amqpConfig, slogLogger)
	broker := consumer.Setup(connection, amqpConfig)
	unitOfWork := db.NewUnitOfWork(bunDB)
	centrifugeConfig := configConfig.Centrifuge
	redisConfig := configConfig.Redis
	client := redis.Setup(ctx, redisConfig, slogLogger)
	node := centrifuge.Setup(ctx, centrifugeConfig, client, slogLogger)
	publisher := centrifugenode.NewPublisher(node, centrifugeConfig)
	init := middleware.Setup(httpServer, api, manager)
	module := user.InitializeUserModule(api, grpcServer, manager, bunDB, outboxBus, broker, unitOfWork, publisher, init)
	bus := event.NewEventBus(connection, broker)
	outboxPublisher := event.NewDefaultOutboxPublisher(bus, broker)
	relayConfig := configConfig.Outbox
	relay := outbox.NewRelay(bunDB, repository, outboxPublisher, relayConfig)
	centrifugenodeInit := centrifugenode.Setup(node, serveMux, manager)
	appApp := newApp(httpServer, configConfig, module, init, slogLogger, client, grpcServer, api, broker, relay, node, centrifugenodeInit)
	return appApp
}

// initialize.go:

func newApp(httpSrv *http.Server, cfg *config.Config, _ user.Module, _ middleware.Init, _ *slog.Logger, _ *redis2.Client, grpcSrv *grpc2.Server, api huma2.API, broker *amqp.Broker, relay *outbox.Relay, centrifugeNode *centrifuge2.Node, _ centrifugenode.Init) *app.App {
	return app.New(httpSrv, cfg, grpcSrv, api, broker, relay, centrifugeNode)
}
